
import type { LeakedKey } from './types';

export const mockLeaks: LeakedKey[] = [
  {
    id: '1',
    keyHash: 'hash_of_AIzaSyA1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S',
    apiKeyPreview: 'AIzaSy...R8S',
    sourceUrl: 'https://github.com/someuser/someproject/blob/main/config.js',
    sourceType: 'github',
    detectionTimestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    status: 'new',
    contextSnippet: 'const firebaseConfig = { apiKey: "AIzaS...", authDomain: "...", ... };',
    keyType: 'Google API Key',
    entropy: 4.5,
    repository: 'someuser/someproject',
    filePath: 'src/config.js',
    isLikelyLeak: null,
    enhancedContext: null,
    isValid: null,
    accessibleResources: null,
    riskLevel: null,
  },
  {
    id: '2',
    keyHash: 'hash_of_AKIAABCDJIJ123456789',
    apiKeyPreview: 'AKIA...6789',
    sourceUrl: 'https://pastebin.com/abcdefg',
    sourceType: 'pastebin',
    detectionTimestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    status: 'investigating',
    contextSnippet: 'AWS_ACCESS_KEY_ID=AKIAABCDJIJ123456789\nAWS_SECRET_ACCESS_KEY=...',
    keyType: 'AWS Access Key',
    entropy: 4.1,
    isLikelyLeak: true,
    enhancedContext: "The snippet clearly shows an AWS Access Key ID paired with what appears to be a secret access key. This is highly indicative of a real leak.",
    lastScanned: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isValid: true,
    accessibleResources: "S3 Buckets (limited access), EC2 instance (metadata only)",
    riskLevel: "medium",
    lastValidatedTimestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    keyHash: 'hash_of_sk_live_aBcDeFgHiJkLmNoPqRsTuVwX',
    apiKeyPreview: 'sk_live_...VwX',
    sourceUrl: 'https://gitlab.com/anotheruser/ecom-backend/-/blob/master/payment.py',
    sourceType: 'gitlab',
    detectionTimestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days ago
    status: 'remediated',
    contextSnippet: "stripe.api_key = os.environ.get('STRIPE_SECRET_KEY', 'sk_live_aBcDeFgHiJkLmNoPqRsTuVwX') # Fallback for local dev",
    keyType: 'Stripe Secret Key',
    entropy: 4.8,
    repository: 'anotheruser/ecom-backend',
    filePath: 'payment.py',
    isLikelyLeak: false,
    enhancedContext: "The key is present as a fallback in an environment variable retrieval, potentially for local development. While present, the primary source is an environment variable, suggesting it might be a placeholder or dev key.",
    lastScanned: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    isValid: false,
    accessibleResources: "None",
    riskLevel: "low",
    lastValidatedTimestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    keyHash: 'hash_of_example_false_positive_key',
    apiKeyPreview: 'example_..._key',
    sourceUrl: 'https://bitbucket.org/devteam/docs/src/master/api_examples.md',
    sourceType: 'bitbucket',
    detectionTimestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    status: 'false_positive',
    contextSnippet: 'Example API Key: Bearer example_false_positive_key_for_documentation_only',
    keyType: 'Generic API Token',
    entropy: 2.5, // Lower entropy
    repository: 'devteam/docs',
    filePath: 'api_examples.md',
    isLikelyLeak: false,
    enhancedContext: "The context explicitly states 'Example API Key' and 'for_documentation_only', strongly indicating this is a false positive.",
    lastScanned: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    isValid: null, // Not applicable for false positive typically
    accessibleResources: null,
    riskLevel: null,
  },
   {
    id: '5',
    keyHash: 'hash_of_another_new_google_key',
    apiKeyPreview: 'AIzaSy...QxYz',
    sourceUrl: 'https://github.com/testuser/public-test/blob/main/app.js',
    sourceType: 'github',
    detectionTimestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 minutes ago
    status: 'new',
    contextSnippet: "const API_KEY = 'AIzaSyaBcDeFgHiJkLmNoPqRsTuVwXyZ'; // TODO: Move to env",
    keyType: 'Google API Key',
    entropy: 4.6,
    repository: 'testuser/public-test',
    filePath: 'app.js',
    isLikelyLeak: null,
    enhancedContext: null,
    isValid: null,
    accessibleResources: null,
    riskLevel: null,
  },
  {
    id: '6',
    keyHash: 'hash_of_FCM_SERVER_KEY_EXAMPLE_123',
    apiKeyPreview: 'AAAA...zYxw',
    sourceUrl: 'https://github.com/some-dev/mobile-app-backend/blob/develop/notifications.py',
    sourceType: 'github',
    detectionTimestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
    status: 'investigating',
    contextSnippet: 'FCM_SERVER_KEY = "AAAAaBcDeFgHiJkLmNoPqRsTuVwXyZ12345_zYxw"',
    keyType: 'Firebase Cloud Messaging Server Key',
    entropy: 4.7,
    repository: 'some-dev/mobile-app-backend',
    filePath: 'notifications.py',
    isLikelyLeak: null,
    enhancedContext: null,
    isValid: null,
    accessibleResources: null,
    riskLevel: null,
  },
  {
    id: '7',
    keyHash: 'hash_of_generic_oauth_token_abcdef123456',
    apiKeyPreview: 'gho_...ef123',
    sourceUrl: 'https://pastebin.com/zyxwvu',
    sourceType: 'pastebin',
    detectionTimestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 hours ago
    status: 'new',
    contextSnippet: 'My temporary OAuth token: gho_abcdef123456ghijklmnopqrstuvwxyzABCD',
    keyType: 'Generic OAuth Token',
    entropy: 4.2,
    isLikelyLeak: null,
    enhancedContext: null,
    isValid: null,
    accessibleResources: null,
    riskLevel: null,
  },
  {
    id: '8',
    keyHash: 'hash_of_darkweb_db_credential_user_pass',
    apiKeyPreview: 'User:...@db',
    sourceUrl: 'some_onion_link/forum/post/12345',
    sourceType: 'dark_web_forum',
    detectionTimestamp: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
    status: 'remediated',
    contextSnippet: 'Database creds: user:admin pass:P@$$wOrd123 host:10.0.0.5 port:5432',
    keyType: 'Database Credentials',
    entropy: 3.9,
    isLikelyLeak: true,
    enhancedContext: "Plaintext database credentials found on a dark web forum.",
    lastScanned: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
    isValid: false, // Assumed remediated means key is no longer valid
    accessibleResources: "Potentially full database access before remediation.",
    riskLevel: "high", // Was high before remediation
    lastValidatedTimestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    keyHash: 'hash_of_another_aws_secret_xyz',
    apiKeyPreview: 'wJalr...secret',
    sourceUrl: 'https://gitlab.com/secops-playground/random-scripts/-/snippets/123',
    sourceType: 'gitlab',
    detectionTimestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    status: 'new',
    contextSnippet: 'export AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEYsecret"',
    keyType: 'AWS Secret Access Key',
    entropy: 4.9,
    repository: 'secops-playground/random-scripts',
    filePath: 'snippets/123',
    isLikelyLeak: null,
    enhancedContext: null,
    isValid: null,
    accessibleResources: null,
    riskLevel: null,
  },
  {
    id: '10',
    keyHash: 'hash_of_sendgrid_api_key_sg',
    apiKeyPreview: 'SG._...1234',
    sourceUrl: 'https://github.com/marketing-tools/email-sender/blob/main/config.yml',
    sourceType: 'github',
    detectionTimestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days ago
    status: 'investigating',
    contextSnippet: 'sendgrid_api_key: SG._xYzAaBcDeFgHiJkLmNoPqRsTuVwXyZ1234.zYxWvUtSrQpOnMlKjIhGfEdCbA',
    keyType: 'SendGrid API Key',
    entropy: 4.8,
    repository: 'marketing-tools/email-sender',
    filePath: 'config.yml',
    isLikelyLeak: null,
    enhancedContext: null,
    isValid: null,
    accessibleResources: null,
    riskLevel: null,
  }
];

    